/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#1d4ed8",
        "on-tertiary-fixed": "#112000",
        "on-tertiary-container": "#8fdb00",
        "tertiary-fixed-dim": "#8fdb00",
        "primary-fixed-dim": "#93c5fd",
        "secondary-container": "#00e3fd",
        outline: "#787589",
        "on-secondary-container": "#00616d",
        "on-primary-fixed-variant": "#1e40af",
        "on-tertiary-fixed-variant": "#314f00",
        "surface-container-high": "#ebe7e7",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "error-container": "#ffdad6",
        "primary-container": "#1e40af",
        background: "#fcf9f8",
        secondary: "#006875",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#313030",
        "surface-container-highest": "#e5e2e1",
        "surface-container": "#f0edec",
        "on-surface-variant": "#474557",
        "on-primary-container": "#bfdbfe",
        "outline-variant": "#c8c4db",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#00daf3",
        primary: "#1d4ed8",
        "on-primary-fixed": "#172554",
        "tertiary-container": "#3a5c00",
        "primary-fixed": "#dbeafe",
        "inverse-primary": "#93c5fd",
        "on-primary": "#ffffff",
        surface: "#fcf9f8",
        "on-secondary-fixed-variant": "#004f58",
        "on-secondary-fixed": "#001f24",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#a8f928",
        "secondary-fixed": "#9cf0ff",
        tertiary: "#294300",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        base: "4px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg-mobile": ["Be Vietnam Pro", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "data-mono": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        sans: ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
